version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: local_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: local_redis
    restart: always
    ports:
      - "6379:6379"
